name: js_wrapping_generator
version: 0.3.0
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: With that package you will be able to easilly generate wrapper for JS library in Dart.
homepage: https://github.com/a14n/dart-js-wrapping
environment:
  sdk: '>=1.20.0 <2.0.0'
dependencies:
  js_wrapping: 0.3.0
  source_gen: ^0.5.1+4
dev_dependencies:
  browser: ^0.10.0
  test: ^0.12.0
dependency_overrides:
  js_wrapping:
    path: ../main_lib