name: js_wrapping
version: 0.0.2
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: With that package you will be able to easilly wrap JS library in Dart.
homepage: https://github.com/a14n/dart-js-wrapping
dependencies:
  meta: any
dev_dependencies:
  browser: any
  unittest: any
