name: js_wrap
author: "Alexandre Ardhuin <alexandre.ardhuin@gmail.com>"
homepage: https://github.com/a14n/dart-js-wrap
version: 0.0.0-dev
description: With that package you will be able to easilly wrap JS library in Dart
dependencies:
  js: '>=0.0.15 <1.0.0'
  unittest: any
  meta: any

