name: js_wrapping
version: 0.2.0-dev
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: With that package you will be able to easilly wrap JS library in Dart.
homepage: https://github.com/a14n/dart-js-wrapping
environment:
  sdk: '>=1.10.0 <2.0.0'
dependencies:
  source_gen: ^0.3.0
dev_dependencies:
  browser: ^0.10.0
  test: ^0.12.0
