name: js_wrapping
version: 0.2.0-dev
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: With that package you will be able to easilly wrap JS library in Dart.
homepage: https://github.com/a14n/dart-js-wrapping
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  analyzer: '>=0.13.0 <0.14.0'
  barback: '>=0.13.0 <0.14.0'
  code_transformers: '>=0.1.4+1 <0.2.0'
dev_dependencies:
  browser: '>=0.9.0 <0.10.0'
  unittest: '>=0.9.0 <0.10.0'
  quiver: '>=0.18.2 <0.19.0'
