targets:
  $default:
    builders:
      js_wrapping_generator:
        generate_for:
          include:
          - example/**

builders:
  js_wrapping_generator:
    import: "package:js_wrapping_generator/builder.dart"
    builder_factories: ["jsWrappingBuilder"]
    build_extensions: {".dart": [".js.g.dart"]}
    auto_apply: dependents
    build_to: source
