name: js_wrapping_generator
version: 0.4.9
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: With that package you will be able to easilly generate wrapper for JS library in Dart.
homepage: https://github.com/a14n/dart-js-wrapping
environment:
  sdk: '>=2.0.0-dev.67.0 <2.0.0'
dependencies:
  analyzer: ^0.32.3
  build: ^0.12.7
  js_wrapping: 0.4.9
  path: ^1.5.1
  source_gen: ^0.8.3
dev_dependencies:
  build_test: ^0.10.2+5
  build_runner: ^0.9.1
  test: ^0.12.0
# dependency_overrides:
#   js_wrapping:
#     path: ../js_wrapping