name: js_wrapping_generator
version: 0.4.4
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: With that package you will be able to easilly generate wrapper for JS library in Dart.
homepage: https://github.com/a14n/dart-js-wrapping
environment:
  sdk: '>=2-0-0-dev <2.0.0'
dependencies:
  analyzer: '>=0.29.0 <0.32.0'
  build: ^0.12.0
  js_wrapping: 0.4.3
  source_gen: ^0.7.4
dev_dependencies:
  browser: ^0.10.0
  build_test: ^0.10.0
  build_runner: ^0.7.9
  test: ^0.12.0
dependency_overrides:
  js_wrapping:
    path: ../js_wrapping