name: js_wrapping_generator
version: 0.5.0
description: >
  With that package you will be able to easilly generate wrapper for JS library
  in Dart.
homepage: https://github.com/a14n/dart-js-wrapping
environment:
  sdk: '>=2.6.0 <3.0.0'
dependencies:
  js_wrapping: 0.5.0
  source_gen: ^0.9.8
dev_dependencies:
  build_test:
  build_runner:
  test: ^1.9.3
dependency_overrides:
  js_wrapping:
    path: ../js_wrapping
