name: js_wrapping_generator
version: 0.7.0
description: >
  With that package you will be able to easilly generate wrapper for JS library
  in Dart.
homepage: https://github.com/a14n/dart-js-wrapping
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  analyzer: ^1.1.0
  build: ^1.6.3
  collection: ^1.15.0
  js_wrapping: 0.7.0
  source_gen: ^0.9.10+3
dev_dependencies:
  build_runner:
  build_test:
  build_web_compilers:
  test:
# dependency_overrides:
#   js_wrapping:
#     path: ../js_wrapping
