name: js_wrapping
version: 0.6.0
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: That package contains elements to easilly wrap JS library in Dart.
homepage: https://github.com/a14n/dart-js-wrapping
environment:
  sdk: '>=2.6.0 <3.0.0'
dependencies:
  js: ^0.6.1+1
